id: vienna_2020

orbit_state: ascending
relative_orbit: 73
instrument_mode: IW

start_date: "2020-06-01"
end_date: "2020-07-01"

bbox:
  - 16.1840505
  - 48.119439
  - 16.578036
  - 48.32185013

download:
  base_path: "$HOME/bucket/WP5_Infrastructure_and_Underground_Safety/InSAR-Daten"   # actual path # when running in container you might have to change that
  max_threads: 8